"""add timestamps to BaseModel

Revision ID: 166a58add2b1
Revises: 302b468ecccb
Create Date: 2025-04-10 14:36:35.992496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166a58add2b1'
down_revision: Union[str, None] = '302b468ecccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ingredients', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('recipe_ingredients', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('recipe_ingredients', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipe_ingredients', 'updated_at')
    op.drop_column('recipe_ingredients', 'created_at')
    op.drop_column('ingredients', 'updated_at')
    op.drop_column('ingredients', 'created_at')
    # ### end Alembic commands ###
